# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39f33815ffa5fa91987fc71e389933ee13c9ee7f0aee1879e76ea839c2d00bb315a22cfbf3513b3a75a21d76c31c95b6d88b566fed8344bc190cb677eb6c0fcd

test:
  secret_key_base: 55a4c06261a8b7ba3d29482e55f521024887a9d22abc39fa04b5f1b9c0379b7b9af367b7421ea62f35fb966ab047a042855c973a4e0d6b4a26188458c03ccf53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
